
/* (QUESTION NUMBER : 7 )*/


SELECT carton.CARTON_ID as "Optimal Carton ID", (carton.len*carton.width*carton.height) as carton_vol ,
((carton.len*carton.width*carton.height- (SELECT SUM(PRODUCT.len*PRODUCT.width*PRODUCT.height*ORDER_ITEMS.PRODUCT_QUANTITY) as pvol
FROM ORDER_ITEMS 
JOIN PRODUCT ON PRODUCT.PRODUCT_ID=ORDER_ITEMS.PRODUCT_ID 
WHERE ORDER_ID=10006))) as vol_diff_carton_prod  
FROM CARTON 
HAVING vol_diff_carton_prod >0
ORDER BY vol_diff_carton_prod LIMIT 1
;


/* (QUESTION NUMBER : 8 )*/

SELECT CUSTOMER_ID,Fullname,ORDER_ID,PRODUCT_QUANTITY FROM 
(SELECT ONLINE_CUSTOMER.CUSTOMER_ID,(ONLINE_CUSTOMER.CUSTOMER_FNAME || " "|| ONLINE_CUSTOMER.CUSTOMER_LNAME) as Fullname,ORDER_HEADER.ORDER_ID,ORDER_ITEMS.PRODUCT_QUANTITY
FROM ONLINE_CUSTOMER
JOIN ORDER_HEADER ON ONLINE_CUSTOMER.CUSTOMER_ID=ORDER_HEADER.CUSTOMER_ID
JOIN ORDER_ITEMS  ON ORDER_HEADER.ORDER_ID=ORDER_ITEMS.ORDER_ID
WHERE ORDER_ITEMS.PRODUCT_QUANTITY>=10)  as SUBQ1

;

/* (QUESTION NUMBER : 9 )*/

SELECT ORDER_HEADER.ORDER_ID,ONLINE_CUSTOMER.CUSTOMER_ID,  (ONLINE_CUSTOMER.CUSTOMER_FNAME || " "|| ONLINE_CUSTOMER.CUSTOMER_LNAME) as Fullname, 
sum(ORDER_ITEMS.PRODUCT_QUANTITY) as totalq_prod
from online_customer
JOIN ORDER_HEADER ON ORDER_HEADER.CUSTOMER_ID = ONLINE_CUSTOMER.CUSTOMER_ID
JOIN ORDER_ITEMS  ON ORDER_ITEMS.ORDER_ID=ORDER_HEADER.ORDER_ID
WHERE ORDER_HEADER.ORDER_STATUS="Shipped"
GROUP BY ORDER_ITEMS.ORDER_ID
HAVING ORDER_ITEMS.ORDER_ID>10060 
;

/* (QUESTION NUMBER : 10 )*/

SELECT Description, tot_q_class,total_price
FROM

(SELECT Description, tot_q_class, total_price
FROM

(SELECT ord,cid, Description, Prod_Price, status, country, sum(totalQ) as tot_q_class ,sum(totalQ*Prod_Price) as total_price
FROM

(SELECT ORDER_HEADER.ORDER_ID as ord,ONLINE_CUSTOMER.CUSTOMER_ID as cid,PRODUCT_CLASS.PRODUCT_CLASS_DESC as Description,
ORDER_ITEMS.PRODUCT_QUANTITY as totalQ, (PRODUCT.PRODUCT_PRICE) as Prod_Price, ORDER_HEADER.ORDER_STATUS as status,ADDRESS.COUNTRY as country
FROM ONLINE_CUSTOMER 
JOIN ADDRESS  ON ONLINE_CUSTOMER.ADDRESS_ID=ADDRESS.ADDRESS_ID 
JOIN ORDER_HEADER ON ORDER_HEADER.CUSTOMER_ID = ONLINE_CUSTOMER.CUSTOMER_ID
JOIN ORDER_ITEMS  ON ORDER_ITEMS.ORDER_ID=ORDER_HEADER.ORDER_ID 
JOIN PRODUCT  ON ORDER_ITEMS.PRODUCT_ID=PRODUCT.PRODUCT_ID
JOIN PRODUCT_CLASS ON PRODUCT.PRODUCT_CLASS_CODE=PRODUCT_CLASS.PRODUCT_CLASS_CODE

WHERE COUNTRY NOT LIKE "INDIA%" and COUNTRY NOT LIKE "USA%") as three

GROUP BY description) as two
) as one
ORDER BY tot_q_class desc limit 1

;