SELECT Description, tot_q_class,total_price
FROM

(SELECT Description, tot_q_class, total_price
FROM

(SELECT ord,cid, Description, Prod_Price, status, country, sum(totalQ) as tot_q_class ,sum(totalQ*Prod_Price) as total_price
FROM

(SELECT ORDER_HEADER.ORDER_ID as ord,ONLINE_CUSTOMER.CUSTOMER_ID as cid,PRODUCT_CLASS.PRODUCT_CLASS_DESC as Description,
ORDER_ITEMS.PRODUCT_QUANTITY as totalQ, (PRODUCT.PRODUCT_PRICE) as Prod_Price, ORDER_HEADER.ORDER_STATUS as status,ADDRESS.COUNTRY as country
FROM ONLINE_CUSTOMER 
JOIN ADDRESS  ON ONLINE_CUSTOMER.ADDRESS_ID=ADDRESS.ADDRESS_ID 
JOIN ORDER_HEADER ON ORDER_HEADER.CUSTOMER_ID = ONLINE_CUSTOMER.CUSTOMER_ID
JOIN ORDER_ITEMS  ON ORDER_ITEMS.ORDER_ID=ORDER_HEADER.ORDER_ID 
JOIN PRODUCT  ON ORDER_ITEMS.PRODUCT_ID=PRODUCT.PRODUCT_ID
JOIN PRODUCT_CLASS ON PRODUCT.PRODUCT_CLASS_CODE=PRODUCT_CLASS.PRODUCT_CLASS_CODE

WHERE COUNTRY NOT LIKE "INDIA%" and COUNTRY NOT LIKE "USA%") as three

GROUP BY description) as two
) as one
ORDER BY tot_q_class desc limit 1

