SELECT CUSTOMER_ID,Fullname,ORDER_ID,PRODUCT_QUANTITY FROM 
(SELECT ONLINE_CUSTOMER.CUSTOMER_ID,(ONLINE_CUSTOMER.CUSTOMER_FNAME || " "|| ONLINE_CUSTOMER.CUSTOMER_LNAME) as Fullname,ORDER_HEADER.ORDER_ID,ORDER_ITEMS.PRODUCT_QUANTITY
FROM ONLINE_CUSTOMER
JOIN ORDER_HEADER ON ONLINE_CUSTOMER.CUSTOMER_ID=ORDER_HEADER.CUSTOMER_ID
JOIN ORDER_ITEMS  ON ORDER_HEADER.ORDER_ID=ORDER_ITEMS.ORDER_ID
WHERE ORDER_ITEMS.PRODUCT_QUANTITY>=10)  as SUBQ1