SELECT ONLINE_CUSTOMER.*, ORDER_HEADER.*

FROM   ONLINE_CUSTOMER  LEFT JOIN ORDER_HEADER 
          ON  ONLINE_CUSTOMER.CUSTOMER_ID=ORDER_HEADER.CUSTOMER_ID 
		  
UNION ALL

SELECT ONLINE_CUSTOMER.*, ORDER_HEADER.*
FROM   ORDER_HEADER 
       LEFT JOIN  ONLINE_CUSTOMER
          ON ORDER_HEADER.CUSTOMER_ID =ONLINE_CUSTOMER.CUSTOMER_ID
WHERE  ORDER_HEADER.CUSTOMER_ID IS NULL 

