SELECT PRODUCT_CLASS_CODE,PRODUCT_ID,PRODUCT_DESC,PRODUCT_PRICE as org_price,
(CASE 
  WHEN PRODUCT_CLASS_CODE=2050 THEN PRODUCT_PRICE+2000
  WHEN PRODUCT_CLASS_CODE=2051 THEN PRODUCT_PRICE+500
  WHEN PRODUCT_CLASS_CODE=2052 THEN PRODUCT_PRICE+600
  ELSE PRODUCT_PRICE
  END) AS "Updated Price"
FROM PRODUCT
ORDER BY PRODUCT_CLASS_CODE DESC;