SELECT PRODUCT_CLASS_DESC, PRODUCT_ID,PRODUCT_DESC, PRODUCT_QUANTITY_AVAIL,
(CASE 
  WHEN PRODUCT_CLASS_DESC="Electronics" OR PRODUCT_CLASS_DESC="Computer" 
  THEN
     (CASE WHEN PRODUCT_QUANTITY_AVAIL=0 THEN "No Stock"
	 	   WHEN PRODUCT_QUANTITY_AVAIL<=10 THEN "Low stock"
	       WHEN PRODUCT_QUANTITY_AVAIL>=11 and PRODUCT_QUANTITY_AVAIL <=30 THEN "In stock"
		   WHEN PRODUCT_QUANTITY_AVAIL>31 THEN "Enough stock"
		   END)
   WHEN PRODUCT_CLASS_DESC="Stationery" OR PRODUCT_CLASS_DESC="Clothes" 
   THEN
     (CASE WHEN PRODUCT_QUANTITY_AVAIL=0 THEN "No Stock"
	 	   WHEN PRODUCT_QUANTITY_AVAIL<=20 THEN "Low stock"
	       WHEN PRODUCT_QUANTITY_AVAIL>=21 and PRODUCT_QUANTITY_AVAIL <=80 THEN "In stock"
		   WHEN PRODUCT_QUANTITY_AVAIL>81 THEN "Enough stock"
	   END)
	ELSE
     (CASE WHEN PRODUCT_QUANTITY_AVAIL=0 THEN "No Stock"
	 	   WHEN PRODUCT_QUANTITY_AVAIL<=15 THEN "Low stock"
	       WHEN PRODUCT_QUANTITY_AVAIL>=16 and PRODUCT_QUANTITY_AVAIL <=50 THEN "In stock"
		   WHEN PRODUCT_QUANTITY_AVAIL>51 THEN "Enough stock"
	   END)
  END) as STOCK
FROM PRODUCT
JOIN PRODUCT_CLASS ON PRODUCT.PRODUCT_CLASS_CODE=PRODUCT_CLASS.PRODUCT_CLASS_CODE