SELECT COUNTRY, count(CITY) as "Number of Cities"
FROM
(
SELECT COUNTRY, CITY
FROM ADDRESS
WHERE COUNTRY NOT LIKE "USA%" AND COUNTRY NOT LIKE "Malaysia%"
)
GROUP BY COUNTRY 
HAVING count(CITY)>1
ORDER BY COUNTRY DESC



