SELECT ONLINE_CUSTOMER.CUSTOMER_ID,  (ONLINE_CUSTOMER.CUSTOMER_FNAME || " "|| ONLINE_CUSTOMER.CUSTOMER_LNAME) as Fullname, ADDRESS.CITY ,
PINCODE,
ORDER_HEADER.ORDER_ID,ORDER_HEADER.ORDER_DATE, PRODUCT_CLASS.PRODUCT_CLASS_DESC, PRODUCT.PRODUCT_DESC, 
(PRODUCT.PRODUCT_PRICE*PRODUCT.PRODUCT_QUANTITY_AVAIL) as subtotal

FROM ONLINE_CUSTOMER
JOIN ADDRESS  ON ONLINE_CUSTOMER.ADDRESS_ID=ADDRESS.ADDRESS_ID 
JOIN ORDER_HEADER ON ORDER_HEADER.CUSTOMER_ID = ONLINE_CUSTOMER.CUSTOMER_ID
JOIN ORDER_ITEMS  ON ORDER_ITEMS.ORDER_ID=ORDER_HEADER.ORDER_ID 
JOIN PRODUCT  ON ORDER_ITEMS.PRODUCT_ID=PRODUCT.PRODUCT_ID
JOIN PRODUCT_CLASS ON PRODUCT.PRODUCT_CLASS_CODE=PRODUCT_CLASS.PRODUCT_CLASS_CODE

WHERE CAST(PINCODE as TEXT) NOT like "%0%" and ORDER_HEADER.ORDER_STATUS="Shipped" 

ORDER BY fullname,ORDER_HEADER.ORDER_DATE,subtotal




