SELECT one.PRODUCT_ID,one.PRODUCT_DESC, sum(one.product_quantity) as total_quantity FROM

(SELECT ORDER_ITEMS.ORDER_ID as od,ORDER_ITEMS.PRODUCT_ID,PRODUCT.PRODUCT_DESC,ORDER_ITEMS.PRODUCT_QUANTITY
   FROM PRODUCT 
   JOIN ORDER_ITEMS ON PRODUCT.PRODUCT_ID=ORDER_ITEMS.PRODUCT_ID ) as one

     JOIN
	 
(SELECT ORDER_ITEMS.ORDER_ID as od,ORDER_ITEMS.PRODUCT_ID,PRODUCT.PRODUCT_DESC,ORDER_ITEMS.PRODUCT_QUANTITY
   FROM PRODUCT 
   JOIN ORDER_ITEMS ON PRODUCT.PRODUCT_ID=ORDER_ITEMS.PRODUCT_ID 
   WHERE ORDER_ITEMS.PRODUCT_ID=201) as two
   
   ON one.od=two.od
   GROUP BY one.PRODUCT_ID
   ORDER BY total_quantity desc limit 1
   
   
  
   
   
  


   
 


  


